export default {
  APPTHEME: "APPTHEME",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
  LOADING: "LOADING",
  USERDETAILS: "USERDETAILS",
  FRIENDREQUESTLIST: "FRIENDREQUESTLIST",
  FRIENDS: "FRIENDS",
  FRIENDSPROFILE: "FRIENDSPROFILE",
};
